### List shopping items
GET http://localhost:8080/shopping-items

### Create new shopping item
POST http://localhost:8080/shopping-items
Content-Type: application/json

{
  "name": "Pizza"
}


### Remove shopping item
DELETE http://localhost:8080/shopping-items/b4351c54-58d1-4e38-8dd2-df09aa53e54a